version: '2.4'

services:
  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 10s
      retries: 3

  message-analyzer:
    image: application/message-analyzer:simple
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl -sS localhost:8081/health || exit 1"
      interval: 20s
      timeout: 60s
      retries: 3
    environment:
      SERVER_PORT: 8081
    ports:
      - "8092:8081"

  medical-monitoring:
    image: application/medical-monitoring:simple
    depends_on:
      message-analyzer:
        condition: service_healthy
    healthcheck:
      test: "curl -sS localhost:8082/health || exit 1"
      interval: 20s
      timeout: 10s
      retries: 3
    environment:
      SERVER_PORT: 8082
    ports:
      - "8093:8082"

  person-service:
    image: application/person-service:simple
    depends_on:
      message-analyzer:
        condition: service_healthy
      medical-monitoring:
        condition: service_healthy
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
#      interval: 20s
#      timeout: 10s
#      retries: 3
    environment:
      SERVER_PORT: 8083
    ports:
      - "8091:8083"
